### ISSUE TITLE
Kindle not connecting

### ISSUE THREAD

**Issue by hsd123456789** [sibbl/hass-lovelace-kindle-4#10]
Hi there,

so i´ve set up everything. But where do i set up the IP of the kindle? How does the Dockerimage know, where to put the dashboard?

**Comment by sibbl** [comment]
Hi,

this project works together with the following rendering software: https://github.com/sibbl/hass-lovelace-kindle-screensaver/

The rendering software uses an internal browser which navigates to the dashboard each minute and generates an image. It's not being sent anywhere but stored there, ready to be fetched from somewhere else whenever necessary.

The 2nd part of the whole software runs on the Kindle. This code is in the repository of this Github issue.
It fetches the generated image from the rendering software and displays it on the Kindle itself.

To fetch it, the Kindle is configured with the URL of the rendering software. This is done in the `config.sh`: https://github.com/sibbl/hass-lovelace-kindle-4/blob/5661d250a8d92d05770ea7f84b9dde62c44addfe/extensions/homeassistant/config.sh#L4

I hope this helps to understand the architecture a bit better?

**Comment by hsd123456789** [comment]
Thanks for the fast response.
So I´ve set everything up. I can fetch a picture of the lovelace dashboard via browser. But the Kindle wont start the script to display the image. I think everythings set up correctly. You know where to look at a possible mistake?

**Comment by dmfarcas** [comment]
@hsd123456789 
here's the issue that I had -- the kindle could not resolve "homeassistant.local" , so the wget would silently fail. 
Please try to use your host's ip address instead of host name.
I figured this by ssh-ing into the kindle and doing a wget manually there. The wget would fail :)
