### ISSUE TITLE
is there any other way to stop/delay the daemon?

### ISSUE THREAD

**Issue by pejotigrek** [sibbl/hass-lovelace-kindle-4#9]
first of all - great work!
I've just jailbreaked an old K4NT, and starting your screensaver + hass-lovelace combo was a piece of cake :)

after few moments I thought I'll change some settings and then I realised, I can't ssh to my kindle ;)
earlier, I had ssh via wifi enabled via KUAL menu [USBnetworking is installed] but to be honest - didn't used that. tried now - without any luck

when I connect my kindle to PC it is found as USB Serial Device COM8, but can't be seen anywhere in network-related settings, does it mean I won't be able to ssh it via usb connection?

also - I tried to reboot the device by long-pressing the power button, but it seems like it just turns off, and when turned on it quickly starts to display my home-assistant dashboard.

shoud I be worried and I need to unbrick it/root again, or there's some solution I can use? [everything - I mean HASS screensaver - work fine, I just can't get into the device ;)]

excuse me if those are uber-n00b questions, as I am indeed a noob in the world of Kindle rooting ;)

**Comment by pejotigrek** [comment]
case closed. after a dozen of tries, I switched from windows pc to ubuntu laptop, tried a couple of times more and suddenly managed to reboot in "regular" usb-drive mode, so I regained control via usb and was able to bring back usbnetwork running :)

**Comment by sibbl** [comment]
Hi @pejotigrek,

sorry for the late reply as I was on vacation in the last weeks.

I'm glad you found a solution. Especially for this case, the device stays awake for a few seconds where it's possible to SSH into the kindle when a new image is fetched and rendered. See the section [Changing config or debugging](https://github.com/sibbl/hass-lovelace-kindle-4#changing-config-or-debugging) in the readme. It seems like you found this exact time window via USB as well. 👍

**Comment by pejotigrek** [comment]
> Hi @pejotigrek,
> 
> sorry for the late reply as I was on vacation in the last weeks.
> 
> I'm glad you found a solution. Especially for this case, the device stays awake for a few seconds where it's possible to SSH into the kindle when a new image is fetched and rendered. See the section [Changing config or debugging](https://github.com/sibbl/hass-lovelace-kindle-4#changing-config-or-debugging) in the readme. It seems like you found this exact time window via USB as well. 👍

hey, no worries! I probably wrote the issue/question too quickly ;)
strange thing is that SSH isn't working anyway.. well, from the windows at last. but I made the delay longer so after reboot I have some more time to go to the menu and change some settings or even plug into pc for "normal" usb-drive mode to do some tweaking :) can't get webhook working tho, so no battery status yet ;)
